# Generated by Django 6.0 on 2025-12-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mark', models.IntegerField()),
                ('sub', models.CharField(max_length=50)),
            ],
        ),
    ]
